"""Teacher->student model-pair registry for the cross-scale safety-transfer experiments.

Single source of truth for the model pairs the pipeline runs on. The original
experiment is Qwen3.5-9B -> Qwen3.5-0.8B; this registry adds the cross-family /
cross-scale extension pairs (Llama-3.x and Qwen3).

How it is used
--------------
* scripts/gen_pair_configs.py renders every per-pair config by loading the
  canonical ``qwen35_9b_to_08b`` template yamls and STRING-REPLACING the model
  identifier tokens below (teacher/student name + tag + the pair_id), then
  setting ``lora.target_modules`` to the pair's architecture-correct list.
  Because output_root / model.path / cross-config references all embed those
  same tokens, one set of replacements re-targets an entire config.
* scripts/15_run_oneclick.py resolves config paths by substituting the same
  tokens into the canonical filenames (``--pair`` arg; default reproduces the
  existing Qwen3.5 filenames byte-for-byte -> fully backward compatible).

Replacement tokens (applied longest-first to avoid partial collisions):
    "qwen35_9b_to_08b" -> pair_id
    "Qwen3.5-9B"       -> teacher.name      "qwen35_9b"  -> teacher.tag
    "Qwen3.5-0.8B"     -> student.name      "qwen35_08b" -> student.tag

NOTE: hyperparameters (top_k / lambda / energy / epochs, incl. the WJB/WGM
per-baseline overrides in 15_run_oneclick.py) are REUSED across pairs by design
(user decision 2026-06-24); only model identity + LoRA target modules change.
"""
from __future__ import annotations

from typing import Dict, List

# Standard HuggingFace attention/MLP projection names for dense Llama-3.x /
# Qwen3 decoder blocks (LoRA targets). The legacy Qwen3.5 pair keeps its own
# (narrower) target set so its existing configs are reproduced unchanged.
_DENSE_TARGET_MODULES: List[str] = [
    "self_attn.q_proj",
    "self_attn.k_proj",
    "self_attn.v_proj",
    "self_attn.o_proj",
    "mlp.gate_proj",
    "mlp.up_proj",
    "mlp.down_proj",
]

_QWEN35_TARGET_MODULES: List[str] = [
    "self_attn.v_proj",
    "self_attn.o_proj",
    "mlp.gate_proj",
    "mlp.up_proj",
    "mlp.down_proj",
]


PAIRS: Dict[str, dict] = {
    # --- Canonical / default pair: templates live under these names already.
    # is_template=True -> the generator NEVER rewrites these (they are the source).
    "qwen35_9b_to_08b": {
        "pair_id": "qwen35_9b_to_08b",
        "teacher": {"name": "Qwen3.5-9B", "path": "../models/Qwen3.5-9B", "tag": "qwen35_9b"},
        "student": {"name": "Qwen3.5-0.8B", "path": "../models/Qwen3.5-0.8B", "tag": "qwen35_08b"},
        "family": "qwen35",
        "target_modules": _QWEN35_TARGET_MODULES,
        "is_template": True,
    },
    # --- Extension pairs (configs generated by scripts/gen_pair_configs.py). ---
    # Confirmed 2026-06-24: use the ALIGNED (Instruct) variants, matching the
    # Qwen pair (chat/aligned weights; the SVD safety axis needs an aligned
    # teacher). NOTE: Llama's suffix convention is OPPOSITE Qwen's -- the aligned
    # model is "-Instruct"; a bare "Llama-3.1-8B" would be the BASE model.
    "llama31_8b_to_1b": {
        "pair_id": "llama31_8b_to_1b",
        "teacher": {"name": "Llama-3.1-8B-Instruct", "path": "../models/Llama-3.1-8B-Instruct", "tag": "llama31_8b"},
        "student": {"name": "Llama-3.2-1B-Instruct", "path": "../models/Llama-3.2-1B-Instruct", "tag": "llama32_1b"},
        "family": "llama3",
        "target_modules": _DENSE_TARGET_MODULES,
    },
    "qwen3_8b_to_06b": {
        "pair_id": "qwen3_8b_to_06b",
        "teacher": {"name": "Qwen3-8B", "path": "../models/Qwen3-8B", "tag": "qwen3_8b"},
        "student": {"name": "Qwen3-0.6B", "path": "../models/Qwen3-0.6B", "tag": "qwen3_06b"},
        "family": "qwen3",
        "target_modules": _DENSE_TARGET_MODULES,
    },
    "qwen3_8b_to_4b": {
        "pair_id": "qwen3_8b_to_4b",
        "teacher": {"name": "Qwen3-8B", "path": "../models/Qwen3-8B", "tag": "qwen3_8b"},
        "student": {"name": "Qwen3-4B", "path": "../models/Qwen3-4B", "tag": "qwen3_4b"},
        "family": "qwen3",
        "target_modules": _DENSE_TARGET_MODULES,
        # The 4B student full-finetune (baseline sft/distill) does not fit one
        # 61GB card (weights 16 + grads 16 + AdamW 32 = ~64GB). device_map="auto"
        # shards it across the 2 dies the run_pairs.sh JOBS ":2" scheduler grants
        # -> fp32 / AdamW / training math UNCHANGED, only weight placement split.
        # Applied by gen_pair_configs to baseline_sft_/baseline_distill_ configs
        # only (ours=LoRA phaseF and eval/nosft fit one card).
        "device_map": "auto",
    },
    "qwen3_4b_to_06b": {
        "pair_id": "qwen3_4b_to_06b",
        "teacher": {"name": "Qwen3-4B", "path": "../models/Qwen3-4B", "tag": "qwen3_4b"},
        "student": {"name": "Qwen3-0.6B", "path": "../models/Qwen3-0.6B", "tag": "qwen3_06b"},
        "family": "qwen3",
        "target_modules": _DENSE_TARGET_MODULES,
    },
}

DEFAULT_PAIR = "qwen35_9b_to_08b"

# Tokens of the canonical pair, longest-first, so replacement never corrupts a
# longer token (e.g. "qwen35_9b" must not be replaced inside "qwen35_9b_to_08b").
_CANON = PAIRS[DEFAULT_PAIR]


def replacement_pairs(pair_id: str) -> List[tuple[str, str]]:
    """Ordered (old, new) string replacements that re-target a canonical config
    (yaml text or a filename) to ``pair_id``. Longest-first to avoid collisions."""
    p = PAIRS[pair_id]
    return [
        ("qwen35_9b_to_08b", p["pair_id"]),       # pair_id (must be first: superstring)
        ("Qwen3.5-0.8B", p["student"]["name"]),    # model names before short tags
        ("Qwen3.5-9B", p["teacher"]["name"]),
        ("qwen35_08b", p["student"]["tag"]),       # short tags last
        ("qwen35_9b", p["teacher"]["tag"]),
    ]


def apply_tokens(text: str, pair_id: str) -> str:
    for old, new in replacement_pairs(pair_id):
        text = text.replace(old, new)
    return text


def is_template(pair_id: str) -> bool:
    return bool(PAIRS.get(pair_id, {}).get("is_template"))


def list_generated_pairs() -> List[str]:
    """Pairs the generator should emit configs for (all except the template)."""
    return [pid for pid in PAIRS if not is_template(pid)]
